version: '3'
volumes:
  backend:

services:
  web:
    build: .
    image: pycones2019:latest
    ports:
      - "5006:80"
    links:
      - backend
    volumes:
      - backend:/usr/src/app/static
      - ./nginx:/etc/nginx/conf.d

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    links:
      - database
    ports:
      - "8000:8000"
    volumes:
      - backend:/usr/src/app/static
    command: ./docker-entrypoint.sh

  database:
    image: postgres:11.1
    environment:
      - POSTGRES_USER=pycones_user
      - POSTGRES_PASSWORD=pycones_pwd
      - POSTGRES_DB=pycones
