version: '3'

services:
  db:
    image:postgres
  web:
    build: .
    command: python backend/manage.py migrate && python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/backend
    # image: pycones2019:latest
    ports:
      - "5006:80"
